services:
  db:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: Vamsi123
      POSTGRES_DB: code_trace_db
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  backend:
    build: ./backend
    depends_on:
      - db
    env_file:
      - .env
    environment:
      DATABASE_URL: postgresql://postgres:Vamsi123@db:5432/code_trace_db
      CORS_ORIGINS: http://localhost:3000,http://127.0.0.1:3000
    ports:
      - "8001:8080"
    restart: always

  frontend:
    build:
      context: ./frontend
      args:
        VITE_API_URL: http://localhost:8001
    depends_on:
      - backend
    ports:
      - "3000:8080"
    restart: always

volumes:
  postgres_data:
